---
title: "Mermaids Part II"
author: "Callie Steffen, Vanessa Guenther, Renee Albreight"
date: "11/26/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#loading packages
library(tidyverse)
library(ggplot2)
library(pwr)
library(kableExtra)
library(knitr)
library(plotly)
library(ggplot2)
library(car)
library(onewaytests)
library(vcdExtra)
library(xtable)
library(ggsignif)
library(hrbrthemes)
library(babynames)
library(viridis)
library(effsize)

###Reading in csv files
faculty<-read_csv("faculty.csv")
grad_enroll<-read_csv("grad_enrollment.csv")
salary<-read_csv("mediansalary.csv")
phD<-read_csv("PhD.csv")
```


1) Male and female graduate enrollment (1967 - 2015). Compare trends in total graduate enroll- ment for males and females (including full-time/part-time and private/public universities) in the United States from 1967 - 2015. Describe your results statistically, graphically and in text.
```{r}
male_female_linegraph<- ggplot(grad_enroll, aes(Year)) +
  geom_line(aes(y=Total_Males, color="Males"))+
  geom_line(aes(y=Total_Females, color="Females"))+
  labs(colour="Gender") +
  guides(fill=guide_legend(title = "Gender"))+
  scale_x_continuous(expand=c(0,0), limits = c(1965,2015), breaks = c(1965,1975,1985,1995,2005,2015))+
  scale_y_continuous(expand = c(0,0), limits=c(250000,2000000),breaks=c(250000,500000,750000,1000000,1250000,1500000,1750000,2000000)) +
   ylab("Number of Students Enrolled") +
  theme_classic()
  

male_female_linegraph


##Regression for  enrollment on year FOR MALES

regression_male_year <- lm(Total_Males~Year, data=grad_enroll)

regression_male_year

##-17112153+9069(year)


plot(regression_male_year)

summary(regression_male_year)
##Multiple R-squared:  0.8545,	Adjusted R-squared:  0.8514 
##F-statistic:   276 on 1 and 47 DF,  p-value: < 2.2e-16

AIC(regression_male_year)
#1210

male_pr<-cor.test(grad_enroll$Year, grad_enroll$Total_Males)

male_pr

###	Pearson's product-moment correlation

##data:  grad_enroll$Year and grad_enroll$Total_Males
#t = 16.612, df = 47, p-value < 2.2e-16
#alternative hypothesis: true correlation is not equal to 0
#95 percent confidence interval:
# 0.8690777 0.9568547
#sample estimates:
#cor 
#0.9243741 



##Regression for enrollment on year FOR FEMALES

regression_female_year <- lm(Total_Females~Year, data = grad_enroll)
##(Intercept) -17112153 9069 year

regression_female_year

plot(regression_female_year)

summary(regression_female_year)
##Multiple R-squared:  0.9827,	Adjusted R-squared:  0.9823 
##F-statistic:  2669 on 1 and 47 DF,  p-value: < 2.2e-16


AIC(regression_female_year)
##1217

female_pr<-cor.test(grad_enroll$Year, grad_enroll$Total_Females)

female_pr

#Pearson's product-moment correlation

#data:  grad_enroll$Year and grad_enroll$Total_Females
#t = 51.659, df = 47, p-value < 2.2e-16
#alternative hypothesis: true correlation is not equal to 0
#95 percent confidence interval:
# 0.9845609 0.9951144
#sample estimates:
      #cor 
#0.9913086 


#####SMOOTH LINE GRAPH????

smooth <-ggplot(grad_enroll, aes(x =Year, y = )) +
  geom_point(aes(y=Total_Females, color="Total_Females"))+
  geom_point(aes(y=Total_Males, color="Total_Males"))+
  geom_smooth(method=lm, se=TRUE, size=.5, color="blue",aes(y=Total_Females)) +
  geom_smooth(method=lm, se=TRUE, size=.5, color="blue",aes(y=Total_Males))+
  ylab("Number of Graduate Students") +
  theme (panel.grid.major = element_blank(),
         panel.grid.minor = element_blank(),panel.background = element_blank(),axis.line = element_line(colour = "black")) +
scale_x_continuous(expand = c(0,0), limits = c(1965,2015), breaks = c(1965,1975,1985,1995,2005,2015))+
  scale_y_continuous(expand = c(0,0), limits=c(250000,2000000),breaks=c(250000,500000,750000,1000000,1250000,1500000,1750000,2000000))+
scale_color_discrete(name = " ") 
        
  


smooth





```





```{r}

female_column<- ggplot(SPhD,aes(x=Year, y=TOTAL_PHDS))+
  geom_col(aes(fill=MAJOR)) +
  theme_classic()
             
             
female_column

linegraph_phD<- ggplot(SPhD,aes(x=Year, y=TOTAL_PHDS, color=MAJOR)) +
  geom_line(aes(fill=MAJOR), size=1) +
  scale_x_continuous(expand = c(0,0), limits=c(1985,2015), breaks = c(1985,2000,2015))+
  scale_y_continuous(expand = c(0,0), limits=c(150,4650),breaks=c(150,650,1150,1650,2150,2650,3150,3650,4150,4650)) +
  ylab("Total Female PhDs") +
  theme_classic()


linegraph_phD



```
3#
```{r}

 #1. The two samples are independent of one another
# The two populations have equal variance or spread
 # Read in two seperate data sets
 employment <- read_csv("Semployment2.csv")
postdoc <- read_csv("Spostdoc2.csv")
postdoc2 <- read_csv("Spostdoc.csv")
employment2  <- read_csv("SEmployment.csv")
 #Explore data Employment 
employment_hist <- ggplot(employment, aes(x = Salary))+
  geom_histogram() +
  facet_wrap(~ Gender)
 employment_hist
 # not ND 
 #Explore Data Postdoc
 postdoc_hist <- ggplot(postdoc, aes(x = Salary))+
  geom_histogram() +
  facet_wrap(~ Gender)
 postdoc_hist
 # not ND
 #is there a significant difference between male and female post-doc position salaries?
#Wilcoxon Signed-Rank: Paired
#he null hypothesis of the Wilcoxon test is usually taken as equal medians
#If we reject the null, that means we have evidence that one distribution is shifted to the left or right of the other. Since we’re assuming our distributions are equal, rejecting the null means we have evidence that the medians of the two populations differ
#(n=15)
 mwu_postdoc <- postdoc %>% 
  wilcox.test(Salary ~ Gender, paired = TRUE, data = .)
mwu_postdoc
 wsr_postdoc = wilcox.test(postdoc2$Male, postdoc2$Female, paired = TRUE)
wsr_postdoc
 #No significant difference - distributions are equal
# what is V!the sum of the ranks in one of both groups.

 #significant different in non-postdoc employment between males and females
 wsr_employment = wilcox.test(employment2$Male, employment2$Female, paired = TRUE)
wsr_employment
 #There is a significant difference
 #EffectSize
test <- cliff.delta(employment2$Male, employment2$Female)
test
 # small effect size Cliff's Delta ( 0.213333) ? 0 -> groups are totally overlapping 
```
Graph
```{r}

e_graph <- ggplot(employment, aes(x = Field, y = Salary ))+
  geom_col(position = "dodge", aes(fill = Gender)) +
  coord_flip()+
  scale_y_continuous(expand = c(0,0), breaks = seq(0, 125000, 25000), limits = c(0,125000)) +
  labs(title = "Median Salaries (Non-PostDoc Positions) ", y = "Median Salary ($)")+
  theme_classic()

e_graph

#only use employment grah in 
#Literature  ?


  

```






#4 Exploring academic salaries for professors in U.S. colleges.

```{r}

fac_salary <- read_csv("faculty_salary.csv")

#Linear Model 1

salary_lm1 <- lm(Salary ~ Sex + Years_Faculty_Service + Rank + Years_Since_PhD + Discipline, data = fac_salary)

summary(salary_lm1)

plot(salary_lm1)



```
```{r}

#linear model 2
salary_lm2 <- lm(Salary ~ Sex + Rank + Years_Since_PhD + Discipline, data = fac_salary)

summary(salary_lm2)

plot(salary_lm2)

```

